import { StyleSheet } from "react-native";
import { CustomColors } from "@/constants/CustomColors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: CustomColors.backgroundDarkest,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    backgroundColor: CustomColors.backgroundDark,
    borderBottomWidth: 1,
    borderBottomColor: CustomColors.textLight + "20",
  },
  headerTitle: {
    color: CustomColors.textLight,
    fontSize: 18,
    fontWeight: "bold",
  },
  closeButton: {
    color: CustomColors.primary,
    fontSize: 16,
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    backgroundColor: CustomColors.backgroundDarkest,
    position: "relative",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: CustomColors.backgroundDarkest,
    padding: 20,
  },
  loadingText: {
    color: CustomColors.textLight,
    marginTop: 10,
    fontSize: 16,
  },
  errorText: {
    color: CustomColors.primary,
    fontSize: 16,
    textAlign: "center",
  },
  noDataText: {
    color: CustomColors.textLight,
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
  },
  customMarker: {
    alignItems: "center",
    width: 60,
    height: 60,
  },
  markerPin: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: '0px 2px 4px rgba(0,0,0,0.4)',
  },
  markerArrow: {
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 12,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    marginTop: -1,
  },
  markerBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#DC143C",
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    paddingHorizontal: 6,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    boxShadow: '0px 2px 3px rgba(0,0,0,0.5)',
  },
  markerBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
  },
  courierMarker: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  courierMarkerInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#2196F3",
    borderWidth: 3,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: '0px 2px 4px rgba(0,0,0,0.4)',
  },
  courierMarkerText: {
    fontSize: 20,
  },
  controlsContainer: {
    position: "absolute",
    bottom: 150,
    left: 20,
    right: 20,
  },
  controlButton: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    boxShadow: '0px 2px 4px rgba(0,0,0,0.3)',
  },
  startButton: {
    backgroundColor: "#4CAF50",
  },
  inProgressButton: {
    backgroundColor: "#FF9800",
  },
  stopButton: {
    backgroundColor: "#F44336",
  },
  controlButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  centerButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: '0px 2px 4px rgba(0,0,0,0.35)',
    zIndex: 10,
  },
  centerButtonText: {
    fontSize: 22,
    lineHeight: 26,
  },
  simulationButton: {
    position: "absolute",
    top: 70,
    right: 16,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#2196F3",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: '0px 2px 4px rgba(0,0,0,0.35)',
    zIndex: 10,
  },
  simulationButtonActive: {
    backgroundColor: "#FFC107",
  },
  simulationButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 20,
  },
  devControls: {
    position: "absolute",
    top: 10,
    left: 10,
    right: 10,
    backgroundColor: "#00000080",
    padding: 8,
    borderRadius: 8,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  devLabel: {
    color: "#FFFFFF",
    fontSize: 14,
  },
});
